services:
  nginx-microservice:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    # @brief Container name
    container_name: nginx-microserver
    # @brief Use the custom image
    image: "nginx-microservice"
    ports:
      # - "80:80"   # HTTP
      - "443:443" # HTTPS
      - "8080:8080" # HTTP
      # - "8443:8443" # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # @brief Load environment variables from the .env file
    env_file:
      - .env
    # @brief Restart policy
    restart: always
    # @brief Define the network used by the service
    networks:
      - vw-network-cluster

networks:
  vw-network-cluster:
    external: true
