services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    # @brief Container name
    container_name: nginx-microserver
    # @brief Use the custom image
    image: "vw-nginx-microservice"
    ports:
      - "${NGINX_PORT_HTTP}:${NGINX_PORT_HTTP}"
      - "${NGINX_PORT_HTTPS}:${NGINX_PORT_HTTPS}"
    volumes:
      # Mount Local Media folder as as media volume
      - ${MEDIA_PATH}:${MEDIA_VOL}
      # Mount Local SSL folder as as media volume
      - ${SSL_PATH}:${SSL_VOL}
      - ${SSL_PATH}/letsencrypt:/etc/letsencrypt
      - ${SSL_PATH}/letsencrypt:/var/www/certbot
      - redis-microserver_redis-volume:/redis-data
      - redis-microserver_redisinsight-data:/usr/src/app/redisinsight
    env_file:
      - .env
    # @brief Restart policy
    restart: always
    # @brief Define the network used by the service
    networks:
      - vw-network-cluster

networks:
  vw-network-cluster:
    external: true

volumes:
  redis-microserver_redis-volume:
    external: true
  redis-microserver_redisinsight-data:
    external: true