services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      # @brief Load environment variables from the .env as arguments to use to build in the Dockerfile
      args:
        - CONDA_ENV_NAME=${CONDA_ENV_NAME}
    # @brief Container name
    container_name: nginx-microserver
    # @brief Use the custom image
    image: "vw-nginx-microservice"
    ports:
      - "${NGINX_PORT_HTTP}:${NGINX_PORT_HTTP}"
    volumes:
      # Mount Local Media folder as as media volume
      - ${MEDIA_PATH}:${MEDIA_VOL}
      # Mount Local SSL folder as as media volume
      - ${SSL_PATH}:${SSL_VOL}
      - ${SSL_PATH}/letsencrypt:/etc/letsencrypt
      - ${SSL_PATH}/letsencrypt:/var/www/certbot
    env_file:
      - .env
    # @brief Restart policy
    restart: always
    # @brief Define the network used by the service
    networks:
      - vw-network-cluster

# @brief Network definition
networks:
  vw-network-cluster:
    external: true